# Deploy

name: Deploy
on:
  push:
    branches: [ main ]

env:
  CI: false

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cpsc455-squadsearch-backend"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
        env:
          NODE_ENV: production
  frontend-deploy:
    needs: backend-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd frontend
          npm install --force
          cd ..
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cpsc455-squadsearch-frontend"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "frontend"
