# CD

name: CD
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2

      -name: frontend lint check
       working-directory: ./
       run: | 
         cd frontend
         npm install
         npm run eslint

      -name: backend lint check
       working-directory: ./
       run: |
         cd backend
         npm install
         eslint .
